services:
  # Backend API Service
  - type: web
    name: thinqscribe-waitlist-api
    env: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://thinqscribe.com
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: web
    name: thinqscribe-waitlist
    env: static
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://thinqscribewaitlist.onrender.com/api
    routes:
      - type: rewrite
        source: /waitlist/*
        destination: /index.html 